version: "3"

services:
  app:
    container_name: category-service
    build: 
      context: ../
      dockerfile: ./docker/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
